#Hugo configuration
title = "blah"
baseURL = "https:\/\/videos.ibm.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
cookiedomain = "ibm.com"
